version = 0.1
default-task = 'build'

[[task]]
name = 'build'
deps = ['rollup:script', 'rollup:worker']
serial = true

[[task]]
name = 'rollup:script'
deps = ['src/*.js']
engine = 'shell'
run = '''
node rollup.script.js
'''

[[task]]
name = 'rollup:worker'
deps = ['src/scripts/*.js']
engine = 'shell'
run = '''
node rollup.worker.js
'''