version = 0.1
default-task = 'build'

[[task]]
name = 'build'
deps = ['rollup:src', 'rollup:scripts']
serial = true

[[task]]
name = 'rollup:src'
deps = ['src/*.js']
engine = 'shell'
run = '''
node rollup/src.js
'''

[[task]]
name = 'rollup:scripts'
deps = ['src/scripts/*.js']
engine = 'shell'
run = '''
node rollup/scripts.js
'''