name: push:main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20.7
      env:
        NODE_ENV: development
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@main
        with:
          ref: main
      - name: Configure .npmrc
        run: |
          pwd
          echo "//registry.npmjs.org/:_authToken=${{secrets.GITHUB_TOKEN}}" > .npmrc
          ls -a
      - name: Publish
        run: |
          npm ci
          npm publish

