name: push:main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20.8
      env:
        NODE_ENV: development
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@main
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          npm ci & npm install -g chomp
          npm version patch --no-git-tag-version
          chomp
          git push origin main
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_PUBLISH_TOKEN}}" > ~/.npmrc
          npm publish --access public
          