name: Publish package to GitHub Packages
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout source
        uses: actions/checkout@main
        with:
          ref: main
      - name: Configure NPM
        uses: actions/setup-node@main
        with:
          node-version: 20
          cache: 'npm'
      - name: Publish pkg
        run: |
          npm ci
          npm publish
