name: Publish package to GitHub Packages
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm publish
